# Generated by Django 2.2.7 on 2019-11-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=220)),
                ('code', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=220)),
                ('url', models.CharField(max_length=220)),
                ('directions', models.ManyToManyField(to='courses.Direction')),
            ],
        ),
    ]
